# Atelier Préparation de Données Tabulaires
## Bâtiments intelligents — capteurs IoT

**Contexte :** une entreprise exploite plusieurs bâtiments intelligents équipés de capteurs IoT.
Chaque capteur collecte des informations sur la température, l'humidité, la qualité de l'air (CO₂),
la consommation énergétique, l'occupation, le type de bâtiment, le mode de climatisation et l'état
du système.

**Objectif :** transformer le fichier brut `smart_building_raw.csv` en un jeu de données propre,
prêt à être utilisé par un algorithme de Machine Learning (prédiction de consommation énergétique
ou détection d'anomalies via la variable `alerte`).

---
# Partie 1 — Explorer les données

<mark style= "background-color: lightblue">**📋Question 1.1** </mark>

 Charger les données CSV

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/smart_building_raw.csv")

<mark style= "background-color: lightblue">**📋Question 1.2** </mark>

Afficher les preméres lignes du dataset

In [3]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

<mark style= "background-color: lightblue">**📋Question 1.3** </mark>

Afficher les derniéres lignes du dataset

In [4]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

<mark style= "background-color: lightblue">**📋Question 1.4** </mark>

Combien d'observations contient le dataset ?

In [5]:
num_observations = df.shape[0]
print(f"Nombre d'observations: {num_observations}")

Nombre d'observations: 507

<mark style= "background-color: lightblue">**📋Question 1.5** </mark>

Combien de variables possède le dataset ?

In [6]:
num_variables = df.shape[1]
print(f"Nombre de variables: {num_variables}")

Nombre de variables: 14

<mark style= "background-color: lightblue">**📋Question 1.6** </mark>